### ISSUE TITLE
Bellman-Ford Algorithm in CPP

### ISSUE THREAD

**Issue by vickyrules** [aritra-tech/Data-Structure-Algorithm#34] opened 2022-07-15 17:04 UTC
Single source shortest path with negative weight edges

**Comment by vickyrules** [comment] 2022-07-15 17:05
@aritra-tech 
this one too please.

**Comment by afreenabegum** [comment] 2022-07-15 19:27
@aritra-tech 
I would like to work on this, please do assign it to me.

**Comment by aritra-tech** [comment] 2022-07-15 20:13
> @aritra-tech I would like to work on this, please do assign it to me.

Sorry, but the issue is created by him so he will only be assigned.

**Comment by afreenabegum** [comment] 2022-07-16 05:50
@aritra-tech  okay, that's fine.

**Comment by aritra-tech** [comment] 2022-07-16 07:14
@vickyrules you can work on this issue now
All the best.

**Closed** 2022-07-16 08:53 UTC
Labels: HSOC22-Level-1, HCSOC22
